// Initial mock data matching db.json
export const INITIAL_DATA = {
  users: [
    {
      id: 1,
      email: "oilhomjonov7@gmail.com",
      password: "odiljon",
      role: "Admin",
      name: "Odiljon Ilhomjonov",
      phone: "+998991370023"
    },
    {
      id: 2,
      email: "manager@uzshop.uz",
      password: "password123",
      role: "Manager",
      name: "Jasur Rahimov",
      phone: "+998935551122"
    },
    {
      id: 3,
      email: "operator@uzshop.uz",
      password: "password123",
      role: "CallCenter",
      name: "Madina Karimova",
      phone: "+998974443322"
    },
    {
      id: 4,
      email: "ali@uzshop.uz",
      password: "password123",
      role: "User",
      name: "Ali Valiyev",
      phone: "+998991234567"
    },
    {
      id: 5,
      email: "nigora@uzshop.uz",
      password: "password123",
      role: "User",
      name: "Nigora Yusupova",
      phone: "+998909876543"
    }
  ],
  categories: [
    { id: "cat-1", name: "Smartfonlar", slug: "smartphones", icon: "Smartphone" },
    { id: "cat-2", name: "Noutbuklar", slug: "laptops", icon: "Laptop" },
    { id: "cat-3", name: "Smart soatlar", slug: "smartwatches", icon: "Watch" },
    { id: "cat-4", name: "Quloqchinlar", slug: "headphones", icon: "Headphones" },
    { id: "cat-5", name: "Aksessuarlar", slug: "accessories", icon: "Cpu" },
    { id: "cat-6", name: "Kiyim va Poyabzal", slug: "clothing", icon: "Shirt" },
    { id: "cat-7", name: "Uy va Oshxona", slug: "home-kitchen", icon: "Home" },
    { id: "cat-8", name: "Sport va Fitnes", slug: "sport", icon: "Dumbbell" },
    { id: "cat-9", name: "Kitoblar", slug: "books", icon: "BookOpen" },
    { id: "cat-10", name: "Go'zallik & Parvarish", slug: "beauty", icon: "Sparkles" },
    { id: "cat-11", name: "Oziq-ovqat va Qahva", slug: "food-coffee", icon: "Coffee" },
    { id: "cat-12", name: "Avtotovarlar", slug: "auto", icon: "Car" },
    { id: "cat-13", name: "Bolalar Dunyosi", slug: "kids", icon: "Baby" }
  ],
  products: [
    {
        "id": "prod-101",
        "categoryId": "cat-1",
        "title": "iPhone 15 Pro Max",
        "price": 1450,
        "discountPrice": 1350,
        "stock": 22,
        "image": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80",
        "description": "256GB Natural Titanium, Super Retina XDR OLED, A17 Pro chip, Dynamic Island.",
        "rating": 4.9,
        "salesCount": 42
    },
    {
        "id": "prod-102",
        "categoryId": "cat-1",
        "title": "Samsung Galaxy S24 Ultra",
        "price": 1380,
        "discountPrice": 1250,
        "stock": 18,
        "image": "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80",
        "description": "512GB Titanium Gray, Galaxy AI imkoniyatlari, 200MP kamera, S-Pen o'rnatilgan.",
        "rating": 4.8,
        "salesCount": 35
    },
    {
        "id": "prod-103",
        "categoryId": "cat-1",
        "title": "Xiaomi 14 Ultra",
        "price": 1100,
        "discountPrice": 990,
        "stock": 34,
        "image": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80",
        "description": "Leica optikasi, 1 dyuymli asosiy sensor, Snapdragon 8 Gen 3, 90W HyperCharge.",
        "rating": 4.7,
        "salesCount": 19
    },
    {
        "id": "prod-104",
        "categoryId": "cat-2",
        "title": "MacBook Pro 16\" M3 Max",
        "price": 3200,
        "discountPrice": 2999,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
        "description": "36GB Unified Memory, 1TB SSD, Liquid Retina XDR displey, Space Black.",
        "rating": 5,
        "salesCount": 14
    },
    {
        "id": "prod-105",
        "categoryId": "cat-2",
        "title": "MacBook Air 15\" M2",
        "price": 1350,
        "discountPrice": 1220,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&auto=format&fit=crop&q=80",
        "description": "Yupqa va yengil korpus, 18 soat batareya quvvati, 500 nit yorqinlik.",
        "rating": 4.8,
        "salesCount": 27
    },
    {
        "id": "prod-106",
        "categoryId": "cat-2",
        "title": "ASUS ROG Zephyrus G16",
        "price": 2400,
        "discountPrice": 2250,
        "stock": 16,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80",
        "description": "Intel Core Ultra 9, RTX 4080 12GB, 240Hz OLED ekran, 32GB RAM, 1TB SSD.",
        "rating": 4.9,
        "salesCount": 11
    },
    {
        "id": "prod-107",
        "categoryId": "cat-3",
        "title": "Apple Watch Ultra 2",
        "price": 890,
        "discountPrice": 820,
        "stock": 9,
        "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80",
        "description": "49mm Titandan korpus, 3000 nit displey, suv osti va tog' sporti uchun tayyor.",
        "rating": 4.9,
        "salesCount": 31
    },
    {
        "id": "prod-109",
        "categoryId": "cat-4",
        "title": "AirPods Max (Space Gray)",
        "price": 590,
        "discountPrice": 520,
        "stock": 10,
        "image": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80",
        "description": "Active Noise Cancellation, Shaxsiy fazoviy ovoz, Hi-Fi akustika va nafis metall dizayn.",
        "rating": 4.7,
        "salesCount": 18
    },
    {
        "id": "prod-110",
        "categoryId": "cat-4",
        "title": "Sony WH-1000XM5",
        "price": 420,
        "discountPrice": 360,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
        "description": "Sanoat yetakchisi bo'lgan shovqinni bostirish (ANC), 30 soat batareya, multipoint ulanish.",
        "rating": 4.9,
        "salesCount": 45
    },
    {
        "id": "prod-111",
        "categoryId": "cat-5",
        "title": "Apple MagSafe Battery Pack",
        "price": 110,
        "discountPrice": 95,
        "stock": 25,
        "image": "/products/magsafe_battery_pack.jpg",
        "description": "iPhone uchun magnitli simsiz quvvatlagich, ixcham va xavfsiz.",
        "rating": 4.5,
        "salesCount": 38
    },
    {
        "id": "prod-112",
        "categoryId": "cat-1",
        "title": "Google Pixel 8 Pro",
        "price": 980,
        "discountPrice": 880,
        "stock": 12,
        "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80",
        "description": "Tensor G3 protsessor, Magic Editor, 7 yillik rasmiy Android yangilanish kafolati.",
        "rating": 4.6,
        "salesCount": 26
    },
    {
        "id": "prod-201",
        "categoryId": "cat-6",
        "title": "Nike Air Force 1 '07 Krossovkasi",
        "price": 130,
        "discountPrice": 115,
        "stock": 24,
        "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80",
        "description": "Klassik oq charm krossovka, qulay amortizatsiya va kundalik kiyish uchun ideal qulaylik.",
        "rating": 4.9,
        "salesCount": 85
    },
    {
        "id": "prod-202",
        "categoryId": "cat-6",
        "title": "Oversize Paxtali Xudi (Unisex)",
        "price": 45,
        "discountPrice": 35,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80",
        "description": "100% paxta, ichi momiq (fleece), qishki va kuzgi mavsum uchun issiq va zamonaviy xudi.",
        "rating": 4.8,
        "salesCount": 112
    },
    {
        "id": "prod-203",
        "categoryId": "cat-6",
        "title": "Tabiiy Charm Kamar & Hamyon To'plami",
        "price": 55,
        "discountPrice": 42,
        "stock": 19,
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80",
        "description": "100% tabiiy buzoq charmidan tayyorlangan, sovg'abop qutida erkaklar aksessuar to'plami.",
        "rating": 4.7,
        "salesCount": 64
    },
    {
        "id": "prod-301",
        "categoryId": "cat-7",
        "title": "DeLonghi Dedica Espresso Kofe Mashinasi",
        "price": 260,
        "discountPrice": 225,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80",
        "description": "15 bar bosimli nasos, sut ko'pirtiruvchi kapuchinator, uyda professional kofe tayyorlash uchun.",
        "rating": 4.9,
        "salesCount": 38
    },
    {
        "id": "prod-302",
        "categoryId": "cat-7",
        "title": "Xiaomi Smart Robot Changyutgich X10+",
        "price": 480,
        "discountPrice": 430,
        "stock": 24,
        "image": "https://images.unsplash.com/photo-1563178406-4cdc2923acbc?w=600&auto=format&fit=crop&q=80",
        "description": "Avtomatik axlat tozalash stansiyasi, nam tozalash, LiDAR navigatsiya va Mi Home ilovasi orqali boshqaruv.",
        "rating": 4.8,
        "salesCount": 29
    },
    {
        "id": "prod-303",
        "categoryId": "cat-7",
        "title": "Eko Keramika Choy Servizi (6 kishilik)",
        "price": 65,
        "discountPrice": 49,
        "stock": 22,
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
        "description": "Qo'lda ishlangan nafis sopol choynak va 6 dona piyola, yog'och patnis bilan birga.",
        "rating": 4.9,
        "salesCount": 51
    },
    {
        "id": "prod-304",
        "categoryId": "cat-7",
        "title": "Ultratovushli Havo Namlagich & Aroma Diffuzor",
        "price": 38,
        "discountPrice": 28,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80",
        "description": "4 litrli hajm, 7 xil LED yorug'lik, efir moylari qo'shish imkoniyati, shovqinsiz tungi rejim.",
        "rating": 4.7,
        "salesCount": 94
    },
    {
        "id": "prod-401",
        "categoryId": "cat-8",
        "title": "Eko TPE Yoga & Fitnes Gilamchasi",
        "price": 32,
        "discountPrice": 24,
        "stock": 30,
        "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80",
        "description": "6mm qalinlik, sirpanmaydigan ikki tomonlama sirt, elkama tasma sumkasi bilan birga.",
        "rating": 4.8,
        "salesCount": 73
    },
    {
        "id": "prod-402",
        "categoryId": "cat-8",
        "title": "Sport Termos-Butilkasi (1000 ml)",
        "price": 25,
        "discountPrice": 19,
        "stock": 45,
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
        "description": "24 soat sovuq, 12 soat issiq saqlovchi ikki qavatli vakuumli zanglamas po'lat.",
        "rating": 4.9,
        "salesCount": 130
    },
    {
        "id": "prod-403",
        "categoryId": "cat-8",
        "title": "Sozlanuvchi Gantellar To'plami (20 kg)",
        "price": 85,
        "discountPrice": 72,
        "stock": 16,
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80",
        "description": "Xrom qoplamali disklar, shtanga ulovchi maxsus bo'g'in va qulay rezina tutqichlar.",
        "rating": 4.8,
        "salesCount": 41
    },
    {
        "id": "prod-501",
        "categoryId": "cat-9",
        "title": "\"Atom Odatlari\" - Jeyms Klir",
        "price": 12,
        "discountPrice": 9,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Kichik o'zgarishlar — ulkan natijalar. Jahon bestselleri, qattiq muqova, o'zbek tilida.",
        "rating": 5,
        "salesCount": 215
    },
    {
        "id": "prod-502",
        "categoryId": "cat-9",
        "title": "\"Boy Ota, Kambag'al Ota\" - Robert Kiyosaki",
        "price": 11,
        "discountPrice": 8,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=80",
        "description": "Moliyaviy savodxonlik bo'yicha dunyodagi 1-raqamli kitob. Qattiq muqovali yangi nashr.",
        "rating": 4.9,
        "salesCount": 180
    },
    {
        "id": "prod-601",
        "categoryId": "cat-10",
        "title": "Dyson Supersonic Soch Quritgichi",
        "price": 520,
        "discountPrice": 480,
        "stock": 7,
        "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80",
        "description": "Intellektual issiqlik nazorati, 5 xil magnitli nasadka, sochlarni kuydirmasdan tez quritish.",
        "rating": 4.9,
        "salesCount": 33
    },
    {
        "id": "prod-602",
        "categoryId": "cat-10",
        "title": "Organik Yuz Teri Parvarishi To'plami",
        "price": 48,
        "discountPrice": 36,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
        "description": "Gialuron kislotali tonik, namlantiruvchi krem va C-vitaminli zardob. 100% tabiiy vositalar.",
        "rating": 4.8,
        "salesCount": 89
    },
    {
        "id": "prod-701",
        "categoryId": "cat-11",
        "title": "Lavazza Qualita Oro Qahva Donalari (1 kg)",
        "price": 28,
        "discountPrice": 22,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80",
        "description": "100% Arabica, Italiya qovurilishi, nozik va gulli hidli premium qahva donalari.",
        "rating": 4.9,
        "salesCount": 145
    },
    {
        "id": "prod-702",
        "categoryId": "cat-11",
        "title": "Tabiiy Tog' Asali (1 kg shisha bankada)",
        "price": 18,
        "discountPrice": 14,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
        "description": "Chotqol tog'larining tabiiy gul va tog' giyohlari asali, 100% toza va shifobaxsh.",
        "rating": 5,
        "salesCount": 92
    },
    {
        "id": "prod-703",
        "categoryId": "cat-11",
        "title": "Lindt Excellence 85% Qora Shokolad (100g)",
        "price": 6,
        "discountPrice": 4.5,
        "stock": 80,
        "image": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80",
        "description": "Haqiqiy Shveysariya qora shokoladi, 85% sof kakao, boy va nafis ta'm.",
        "rating": 4.8,
        "salesCount": 210
    },
    {
        "id": "prod-801",
        "categoryId": "cat-12",
        "title": "70mai 4K A810 Smart Video-Registrator",
        "price": 165,
        "discountPrice": 145,
        "stock": 18,
        "image": "/products/dashcam_4k.jpg",
        "description": "Sony Starvis 2 sensori, 4K HDR tasvir, GPS, ADAS xavfsizlik tizimi va Wi-Fi ulanish.",
        "rating": 4.9,
        "salesCount": 48
    },
    {
        "id": "prod-802",
        "categoryId": "cat-12",
        "title": "Baseus Simsiz Avtomobil Changyutgichi (A3)",
        "price": 48,
        "discountPrice": 39,
        "stock": 27,
        "image": "/products/car_vacuum.jpg",
        "description": "15000Pa kuchli tortish quvvati, metall korpus, yorug'lik chirog'i va Type-C quvvatlash.",
        "rating": 4.7,
        "salesCount": 65
    },
    {
        "id": "prod-803",
        "categoryId": "cat-12",
        "title": "Xiaomi Mi Portable Elektr Shina Nasosi 2",
        "price": 42,
        "discountPrice": 34,
        "stock": 34,
        "image": "/products/tire_inflator.jpg",
        "description": "Avtomatik bosim o'lchash va to'xtatish, ixcham akkumulyatorli, velosiped va to'plarga ham mos.",
        "rating": 4.8,
        "salesCount": 88
    },
    {
        "id": "prod-901",
        "categoryId": "cat-13",
        "title": "Lego City Politsiya Boshqarmasi To'plami",
        "price": 75,
        "discountPrice": 64,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=600&auto=format&fit=crop&q=80",
        "description": "668 ta detal, vertolyot, mashinalar va mini-figuralar bilan original Lego konstruktori.",
        "rating": 4.9,
        "salesCount": 37
    },
    {
        "id": "prod-902",
        "categoryId": "cat-13",
        "title": "Katta Yumshoq Ayiqcha Teddy (120 sm)",
        "price": 45,
        "discountPrice": 35,
        "stock": 21,
        "image": "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80",
        "description": "Gipoallergen momiq mato, bolalar va sovg'a uchun juda yoqimli va xavfsiz.",
        "rating": 4.8,
        "salesCount": 52
    },
    {
        "id": "prod-903",
        "categoryId": "cat-13",
        "title": "Rangli LCD Chizish Plansheti (12 dyuym)",
        "price": 14,
        "discountPrice": 9.9,
        "stock": 60,
        "image": "/products/kids_lcd_tablet.jpg",
        "description": "Ko'zga ziyon yetkazmaydigan rangli ekran, bitta tugma bilan tozalash, stilus bilan.",
        "rating": 4.7,
        "salesCount": 140
    },
    {
        "id": "prod-305",
        "categoryId": "cat-7",
        "title": "Tefal Ingenio Non-Stick Tovalar To'plami (3 dona)",
        "price": 95,
        "discountPrice": 79,
        "stock": 16,
        "image": "/products/tefal_ingenio_pans.jpg",
        "description": "Yechiluvchi universal tutqich, Thermo-Signal harorat indikatori, pechda ham ishlatish mumkin.",
        "rating": 4.8,
        "salesCount": 44
    },
    {
        "id": "prod-306",
        "categoryId": "cat-7",
        "title": "Braun MultiQuick 7 Zanglamas Blender (1000W)",
        "price": 88,
        "discountPrice": 74,
        "stock": 19,
        "image": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&auto=format&fit=crop&q=80",
        "description": "ActiveBlade texnologiyasi, maydalagich kosa, ko'pirtiruvchi venchik va o'lchov stakani.",
        "rating": 4.9,
        "salesCount": 58
    },
    {
        "id": "prod-204",
        "categoryId": "cat-6",
        "title": "Issiq Erkaklar Qishki Parka Kurtkasi",
        "price": 98,
        "discountPrice": 82,
        "stock": 21,
        "image": "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&auto=format&fit=crop&q=80",
        "description": "Suv va shamol o'tkazmaydigan membranali mato, tabiiy par to'ldiruvchi, yechiluvchi kapyushon.",
        "rating": 4.8,
        "salesCount": 49
    },
    {
        "id": "prod-205",
        "categoryId": "cat-6",
        "title": "Klassik Ayollar Teri Elka Sumkasi",
        "price": 65,
        "discountPrice": 49,
        "stock": 26,
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
        "description": "Sifatli ekologik charm, bir nechta qulay bo'limlar, tilla rang metall furnitura.",
        "rating": 4.9,
        "salesCount": 67
    },
    {
        "id": "prod-206",
        "categoryId": "cat-6",
        "title": "Erkaklar Tabiiy Teri Oksford Poyabzali (Qora)",
        "price": 280,
        "discountPrice": 240,
        "stock": 20,
        "image": "/products/mens_oxford_shoes.jpg",
        "description": "Yuqori sifatli tabiiy buzoq terisidan ishlangan klassik erkaklar poyabzali. Rasmiy tadbirlar va kundalik ofis uslubi uchun.",
        "rating": 5,
        "salesCount": 22
    },
    {
        "id": "prod-603",
        "categoryId": "cat-10",
        "title": "Dior Sauvage Erkaklar Parfyumi (100 ml)",
        "price": 145,
        "discountPrice": 129,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80",
        "description": "Bergamot, qalampir va ambra notalari bilan dunyodagi eng mashhur va jozibador parfyum.",
        "rating": 4.9,
        "salesCount": 84
    },
    {
        "id": "prod-604",
        "categoryId": "cat-10",
        "title": "Chanel Coco Mademoiselle (100 ml)",
        "price": 160,
        "discountPrice": 142,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&auto=format&fit=crop&q=80",
        "description": "Apelsin, atirgul va pachuli notalari bilan nozik, nafis va esda qolarli ayollar ifori.",
        "rating": 5,
        "salesCount": 63
    },
    {
        "id": "prod-605",
        "categoryId": "cat-10",
        "title": "Oral-B iO Series 9 Smart Tish Cho'tkasi",
        "price": 195,
        "discountPrice": 170,
        "stock": 30,
        "image": "/products/oral_b_smart_toothbrush.jpg",
        "description": "Magnit mikro-vibratsiya texnologiyasi, sun'iy intellektli tozalash tahlili, sayohat zaryadlovchi g'ilofi.",
        "rating": 4.9,
        "salesCount": 36
    },
    {
        "id": "prod-503",
        "categoryId": "cat-9",
        "title": "\"Stiv Jobs\" — Uolter Ayzekson",
        "price": 15,
        "discountPrice": 12,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
        "description": "Apple asoschisining yagona rasmiy biografiyasi. O'zbek tiliga o'girilgan to'liq nashr.",
        "rating": 4.9,
        "salesCount": 95
    },
    {
        "id": "prod-504",
        "categoryId": "cat-9",
        "title": "\"Alkimyogar\" — Paulo Koelo (Jahon Bestselleri)",
        "price": 45,
        "discountPrice": 36,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&auto=format&fit=crop&q=80",
        "description": "O'z orzulari ortidan borgan cho'pon Santyagoning afsonaviy sayohati. Dunyoning 80 dan ortiq tillariga tarjima qilingan asar.",
        "rating": 4.8,
        "salesCount": 40
    },
    {
        "id": "prod-404",
        "categoryId": "cat-8",
        "title": "Garmin Forerunner 265 GPS Sport Soati",
        "price": 430,
        "discountPrice": 390,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=600&auto=format&fit=crop&q=80",
        "description": "Yorqin AMOLED displey, professional yugurish va yurak urishi dinamikasi, 13 kunlik batareya.",
        "rating": 4.9,
        "salesCount": 21
    },
    {
        "id": "prod-405",
        "categoryId": "cat-8",
        "title": "Yonex Badminton Raketkalari & Volanlar To'plami",
        "price": 55,
        "discountPrice": 42,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&auto=format&fit=crop&q=80",
        "description": "Uglerod tolali engil 2 ta raketka, 6 ta volan va qulay tashish sumkasi.",
        "rating": 4.7,
        "salesCount": 55
    },
    {
        "id": "prod-1001",
        "categoryId": "cat-1",
        "title": "Xiaomi Redmi Note 13 Pro+ 5G (Midnight Black)",
        "price": 980,
        "discountPrice": 890,
        "stock": 19,
        "image": "https://images.unsplash.com/photo-1598327105854-c8674faddf79?w=600&auto=format&fit=crop&q=80",
        "description": "200 MP flagman kamera, 120W giper-tezkor quvvatlash, egilgan 1.5K 120Hz AMOLED displey va IP68 suvdan himoya.",
        "rating": 4.8,
        "salesCount": 38
    },
    {
        "id": "prod-1002",
        "categoryId": "cat-1",
        "title": "OnePlus 12 512GB (Silky Black)",
        "price": 860,
        "discountPrice": 790,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&q=80",
        "description": "Snapdragon 8 Gen 3, Hasselblad 4-avlod kamerasi, 100W SUPERVOOC tez zaryad.",
        "rating": 4.7,
        "salesCount": 29
    },
    {
        "id": "prod-1003",
        "categoryId": "cat-2",
        "title": "Dell XPS 15 9530 OLED",
        "price": 2100,
        "discountPrice": 1950,
        "stock": 12,
        "image": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
        "description": "Intel Core i7-13700H, 3.5K OLED sensorli ekran, 32GB RAM, RTX 4060, 1TB SSD.",
        "rating": 4.9,
        "salesCount": 16
    },
    {
        "id": "prod-1004",
        "categoryId": "cat-2",
        "title": "Lenovo Legion Pro 5 Gaming",
        "price": 1750,
        "discountPrice": 1599,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&auto=format&fit=crop&q=80",
        "description": "AMD Ryzen 7 7745HX, RTX 4070 8GB, 240Hz WQXGA, 32GB DDR5, 1TB PCIe SSD.",
        "rating": 4.8,
        "salesCount": 22
    },
    {
        "id": "prod-1005",
        "categoryId": "cat-3",
        "title": "Samsung Galaxy Watch 6 Classic 47mm",
        "price": 380,
        "discountPrice": 340,
        "stock": 20,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
        "description": "Aylanuvchi mexanik bezel, EKG, qon bosimi va uyqu sifatini chuqur tahlil qilish.",
        "rating": 4.7,
        "salesCount": 47
    },
    {
        "id": "prod-1006",
        "categoryId": "cat-3",
        "title": "Huawei Watch GT 4 Steel Edition",
        "price": 270,
        "discountPrice": 235,
        "stock": 30,
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80",
        "description": "Klassik metall korpus, 14 kunlik avtonom ishlash, 100+ sport rejimlari.",
        "rating": 4.8,
        "salesCount": 51
    },
    {
        "id": "prod-1007",
        "categoryId": "cat-4",
        "title": "Bose QuietComfort Ultra Quloqchin",
        "price": 440,
        "discountPrice": 399,
        "stock": 16,
        "image": "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop&q=80",
        "description": "Dunyodagi eng ilg'or shovqinni so'ndirish (ANC), Spatial Audio va a'lo qulaylik.",
        "rating": 4.9,
        "salesCount": 33
    },
    {
        "id": "prod-1008",
        "categoryId": "cat-4",
        "title": "Marshall Major IV Simsiz Quloqchin",
        "price": 160,
        "discountPrice": 139,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=600&auto=format&fit=crop&q=80",
        "description": "80+ soatlik rekord batareya, klassik vintage rok dizayni, simsiz zaryadlash.",
        "rating": 4.8,
        "salesCount": 84
    },
    {
        "id": "prod-1009",
        "categoryId": "cat-5",
        "title": "Anker Prime 200W Power Bank 20000mAh",
        "price": 140,
        "discountPrice": 119,
        "stock": 35,
        "image": "/products/anker_prime_powerbank.jpg",
        "description": "Noutbuk va telefonlarni bir vaqtda to'liq quvvatlaydigan smart displeyli batareya.",
        "rating": 4.9,
        "salesCount": 62
    },
    {
        "id": "prod-1010",
        "categoryId": "cat-6",
        "title": "Nike Air Jordan 1 Retro High OG",
        "price": 210,
        "discountPrice": 185,
        "stock": 18,
        "image": "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80",
        "description": "Haqiqiy charm, afsonaviy Chicago ranglar uyg'unligi, har kuni kiyish uchun qulay.",
        "rating": 4.9,
        "salesCount": 75
    },
    {
        "id": "prod-1011",
        "categoryId": "cat-6",
        "title": "New Balance 574 V3 Classic",
        "price": 120,
        "discountPrice": 98,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80",
        "description": "Zamsh va to'rli nafas oluvchi material, ENCAP zarbaga qarshi yumshoq taglik.",
        "rating": 4.7,
        "salesCount": 63
    },
    {
        "id": "prod-1012",
        "categoryId": "cat-7",
        "title": "Philips Airfryer XXL Smart Sensing (Yog'siz Qovurgich)",
        "price": 320,
        "discountPrice": 279,
        "stock": 22,
        "image": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
        "description": "Yog'siz va sog'lom pishiruvchi raqamli aqlli aerogrill. Smart Sensing texnologiyasi harorat va vaqtni o'zi boshqaradi.",
        "rating": 4.9,
        "salesCount": 44
    },
    {
        "id": "prod-1013",
        "categoryId": "cat-7",
        "title": "Dyson V15 Detect Simsiz Vertikal Changyutgich",
        "price": 680,
        "discountPrice": 599,
        "stock": 12,
        "image": "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80",
        "description": "Lazerli mikroskopik chang aniqlash tizimi, 240 AW kuchli so'rish quvvati va 60 daqiqalik avtonom batareya.",
        "rating": 4.8,
        "salesCount": 27
    },
    {
        "id": "prod-1014",
        "categoryId": "cat-7",
        "title": "Tefal OptiGrill+ XL Aqlli Elektr Gril (2000W)",
        "price": 280,
        "discountPrice": 245,
        "stock": 15,
        "image": "/products/tefal_smart_grill.jpg",
        "description": "Go'sht pishirish darajasini avtomatik aniqlaydigan aqlli sensorli elektr gril. 9 ta avtomatik dastur va yopishmas qoplama.",
        "rating": 4.8,
        "salesCount": 39
    },
    {
        "id": "prod-1015",
        "categoryId": "cat-8",
        "title": "Bowflex SelectTech Sozlanuvchi Gantellar",
        "price": 420,
        "discountPrice": 369,
        "stock": 10,
        "image": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80",
        "description": "2 kg dan 24 kg gacha 15 xil vaznga tez o'zgaruvchi patentlangan uy trenajori.",
        "rating": 4.9,
        "salesCount": 31
    },
    {
        "id": "prod-1016",
        "categoryId": "cat-9",
        "title": "\"Muvaffaqiyatli Insonlarning 7 Ko'nikmasi\" — Stiven Kovi",
        "price": 18,
        "discountPrice": 14,
        "stock": 120,
        "image": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
        "description": "Shaxsiy samaradorlik va yetakchilik bo'yicha dunyodagi №1 eng mashhur biznes qo'llanma. Qattiq muqovali to'liq nashr.",
        "rating": 5,
        "salesCount": 320
    },
    {
        "id": "prod-1017",
        "categoryId": "cat-9",
        "title": "\"Psixologiya va Pul\" - Morgan Hausel",
        "price": 16,
        "discountPrice": 12,
        "stock": 85,
        "image": "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80",
        "description": "Boylik, ochko'zlik va baxt haqida abadiy saboqlar to'plami.",
        "rating": 4.9,
        "salesCount": 210
    },
    {
        "id": "prod-1018",
        "categoryId": "cat-10",
        "title": "Dyson Airwrap Multi-Styler Complete Long (Nikelli mis)",
        "price": 540,
        "discountPrice": 489,
        "stock": 14,
        "image": "/products/dyson_airwrap_set.jpg",
        "description": "Sochni qizdirmasdan Coanda effekti bilan turmaklaydigan premium multi-stayler to'plami. Maxsus charm saqlash qutisi bilan.",
        "rating": 5,
        "salesCount": 58
    },
    {
        "id": "prod-1019",
        "categoryId": "cat-10",
        "title": "CeraVe Dermatologik Yuz Parvarishi To'plami",
        "price": 45,
        "discountPrice": 36,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&auto=format&fit=crop&q=80",
        "description": "3 xil muhim keramidlar va gialuron kislotasi bilan to'yintirilgan namlantiruvchi krem va gel.",
        "rating": 4.8,
        "salesCount": 140
    },
    {
        "id": "prod-1020",
        "categoryId": "cat-11",
        "title": "Illy Espresso Klassik Donador Qahva (250g)",
        "price": 28,
        "discountPrice": 22,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80",
        "description": "100% Arabika oliy navli donador Italiya qahvasi. O'rtacha qovurilgan, yumshoq karamel ta'mga ega metall bankada.",
        "rating": 4.9,
        "salesCount": 180
    },
    {
        "id": "prod-1021",
        "categoryId": "cat-12",
        "title": "70mai Dash Cam Omni 360° Smart Registrator",
        "price": 185,
        "discountPrice": 159,
        "stock": 25,
        "image": "/products/dashcam_omni_360.jpg",
        "description": "360 daraja aylanuvchi kamera, sun'iy intellekt xavfsizlik nazorati, tungi aniq tasvir.",
        "rating": 4.8,
        "salesCount": 67
    },
    {
        "id": "prod-1022",
        "categoryId": "cat-13",
        "title": "LEGO Creator Expert Politsiya Mahkamasi 10278",
        "price": 240,
        "discountPrice": 210,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&auto=format&fit=crop&q=80",
        "description": "2923 bo'lakli kolleksion modul konstruktor, 5 ta minifigurka va ajoyib detallar.",
        "rating": 5,
        "salesCount": 35
    }
]
};
